language: rust

rust:
  - stable
  - nightly

os:
  - linux
  - osx

cache:
  timeout: 360
  cargo: true

before_cache:
  - chmod -R a+r $HOME/.cargo

env:
  global:
    - CRATE_NAME=upt

test_script:
  - cargo test
  - cargo run -- list -i

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "Kf1eO6os601ePkzpjSeW/cBViNtQd90DvX4h6Rv5h8NXT9qp3I1EC9pCrQlI4b29vL/FwZOSrE8EW9yEavITDsYWGmd8WT/z+PdIY2PsHUFGnezsEPzBYjWcp1d/E3SN4By6imF6/NSeMU3ESYeduHyULcot5aUdPQuARDfVRsadToeYuksAhQA4aIiyZ3qHA7ILD9C+r8k3QCmYc5N85FgfkrvJYTFQnAkTMo6U7yux1dMek+iyyVO/1nR6ETd20SiC9AgDdpvp/iVjUzkG+zNKDLkjiIShHK8EDT/pAVgFmEPwi88EIojnQNbG5fjL4gd+Svu6TZfuLnYdUY6d7rn+GZ+RyLm/3OYJaOuGJvBqIdFPryEcXQQPNvIvD482V+0rYUves9f8hkIJF70F3EHe2pygJOR1Ca9pz1/hpgeYo6dRjIM+mHGnJr3ZxZHMU1Ho4/E/NQBzhzGSwmp9fTVaONFxSFHveUvRkJEbB1L76kVmSAFK7V4rPMv12kMjL9Cs9RQoyDFCiNRiRoLo9OeGakl+nYT28WRj+tXTMMKK5QGxb38eYrNhIfjE8HTCmsTb9pnXGLaa8PK5B8dh2dgqvKGlYiqGx/2jx8ec4NPTagt9gykE9UEHry+usfDvieXsgxSfQNuefGsOLFBPq/4k/4WYNibIyIolicESaVI="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
